### ISSUE TITLE
change 'has scheme of nomen' property template

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#149]
### Resource Template Label or ID

UWSINOPIA WAU rdaNomen accessPoint CAMS

### Problem using the resource template, or request a change

**rdaNomen accessPoint RT** > [**has scheme of nomen**](https://access.rdatoolkit.org/Content/Index?externalId=en-US_ala-da6ba21b-69b7-3848-b438-fb0dbb9c859a&highlight=has&highlight=scheme&highlight=of&highlight=nomen)\* PT currently set as:

- Property template type: URI
- Default value: Library of Congress Names - http://id.loc.gov/authorities/names

\**Toolkit link*

This value doesn't seem quite right, per discussion at 2023-07-11 meeting. Let's use value(s) from the [LC Description Conventions](http://id.loc.gov/vocabulary/descriptionConventions) vocabulary as suggested by @AdamSchiff .

Configure PT as follows:

**FIRST CHOICE**:
- If lookup to Description Conventions vocab is available, configure PT as lookup
- Configure default IRI/label as:
   - http://id.loc.gov/vocabulary/descriptionConventions/rda
   - Resource description and access

**SECOND CHOICE**:
- If no lookup to Description Conventions vocab is available, configure PT as URI
- Configure default IRI/label as:
   - http://id.loc.gov/vocabulary/descriptionConventions/rda
   - Resource description and access
- Add a guidance_set > general content indicating that if a different value is needed, value(s) should be taken from the [LC Description Conventions](http://id.loc.gov/vocabulary/descriptionConventions) vocabulary

### Any other relevant details

If I'll go through prop_set editing with @junghaelee this might be a good issue to work on
CC @cspayne

**Comment by briesenberg07** [comment]
Following up with @AdamSchiff @gerontakos @pan-zhuo @CECSpecialistI @junghaelee @JianPLee for feedback.
If no objections, @cspayne will you reconfigure PT as above next week (2023-07-24)?

**Comment by AdamSchiff** [comment]
I added a few more statements to the item for Suzzallo and Allen Libraries Stacks: https://www.wikidata.org/wiki/Q120734816

There's the "code" property that I used for the location code.

If we want to go this way so that Sinopia can do a lookup in Wikidata, we'll need to create a 326 items for all the codes that we use.

The broad list of codes for library buildings used in Alma is at https://staff.lib.uw.edu/operations/arcs/for-arcs-staff/alma-record-standards/physical-inventory/holdings-records/alma-library-and-location-codes

For specific locations, there is a list of the most used codes at https://staff.lib.uw.edu/operations/cas/for-all-staff/management/location-codes.  And the comprehensive list is a spreadsheet: https://staff.lib.uw.edu/operations/cas/for-all-staff/management/alma-location-codes.xlsx.

I've created a second item for CAMS stacks: https://www.wikidata.org/wiki/Q120734968

Can you think of any other properties that we would want to include in these items if we do go this route?

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by cspayne** [comment]
@briesenberg07 @AdamSchiff @gerontakos  @pan-zhuo  @CECSpecialistI  @junghaelee  @JianPLee 

Description Conventions is available as a lookup, so this change can be implemented if there are no objections.

**Comment by AdamSchiff** [comment]
I used it earlier in my nomen!

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by cspayne** [comment]
> Following up with @AdamSchiff @gerontakos @pan-zhuo @CECSpecialistI @junghaelee @JianPLee for feedback. If no objections, @cspayne will you reconfigure PT as above next week (2023-07-24)?

@briesenberg07 
Would you like this done _by_ 2023-07-24 or did you mean to wait until then to implement it?
