### ISSUE TITLE
Consolidate PTs in UWSINOPIA:WAU:rdaItem:printMonograph:CAMS

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#174]
@junghae lee let's work on this when we [meet on 9/21](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2023_meetings_technical_and_project_management.docx?d=w75934e218247459b93cd4df551390895&csf=1&web=1&e=3hCbqX&nav=eyJoIjoiMTk1NzA3MTM0OSJ9).

**Comment by cspayne** [comment]
How I consolidate PTs: 

Set-up: 
1. Have the resource template open in Sinopia Stage
2. Have the prop_set file open in two places (I use oXygen and Visual Studio, you could likely do two windows within oXygen as well) - this just makes it easier to copy and past instead of navigating up and down the file within one window. 
3. In the file open in oXygen, find the new property template (for person elements - "has related person of work")
4. If not there, add the <sinopia> element to this prop and top-level elements (institution, resource, format, user) - make use of oXygen's content completion!
5. Using Sinopia Stage, find the first 'person' prop currently in the resource template and search the prop_set file to find the form order, set the form order for the new property template to that value (if you want it in the same order)
6.  Add the multiple_prop element
7. Add the repeatable element as true
9. Add the input type - this can also be copied from the first 'person' prop currently in the RT, they should all be the same
```xml
<sinopia>
         <uwsinopia:toolkit url="https://access.rdatoolkit.org/en-US_ala-24dc7885-581b-34da-868c-6a0a665ce90c"/>
         <uwsinopia:implementation_set localid_implementation_set="uwmaps_rdaw_p10k_wP10312_is_d2e4085">
            <uwsinopia:institution>WAU</uwsinopia:institution>
            <uwsinopia:resource>rdaWork</uwsinopia:resource>
            <uwsinopia:format>printMonograph</uwsinopia:format>
            <uwsinopia:user>CAMS</uwsinopia:user>
            <uwsinopia:form_order>0.25</uwsinopia:form_order>
           <uwsinopia:multiple_prop> </uwsinopia:multiple_prop>
            <uwsinopia:repeatable>true</uwsinopia:repeatable>
            <uwsinopia:lookup_pt>
               <uwsinopia:authorities>
                  <uwsinopia:authority_urn>LOC person [names (rwo)] (QA)</uwsinopia:authority_urn>
                  <uwsinopia:authority_urn>LOC organization [names (rwo)] (QA)</uwsinopia:authority_urn>
                  <uwsinopia:authority_urn>LOC family [names (rwo)] (QA)</uwsinopia:authority_urn>
                  <uwsinopia:authority_urn>GETTY_ULAN (QA)</uwsinopia:authority_urn>
                  <uwsinopia:authority_urn>ISNI (QA)</uwsinopia:authority_urn>
                  <uwsinopia:authority_urn>Wikidata (QA)</uwsinopia:authority_urn>
               </uwsinopia:authorities>
            </uwsinopia:lookup_pt>
         </uwsinopia:implementation_set>
```

Moving PTs:
1. In Sinopia Stage, go to the first instance of a 'person' agent property and copy the label (e.g. 'has artist person')
2. In one window of the prop_set file, ctrl+f search the label to find the prop
3. Copy the prop_iri
4. In the other window, go to the 'has related person' prop's multiple prop element and add a property selection element
6. Paste the prop_iri into the property_iri attribute
7. Set the xml:lang attribute to "en"
8. Back in the first window, copy the label
9. In the second window, paste the label in the property_selection element
```xml
<uwsinopia:multiple_prop>
     <uwsinopia:property_selection property_iri="http://rdaregistry.info/Elements/w/P10451" xml:lang="en">has artist person</uwsinopia:property_selection>
</uwsinopia:multiple_prop>
```
11. Repeat for each 'person' property in the resource template, including those in drop-down templates - I use the Sinopia Stage window to get the labels to ensure I don't miss any all_subprops drop-down properties. 
12. Once everything has been copied, (and for agents the 'has related family of work' and 'has related corporate body of work'  property templates have been copied as well), delete the old property template Sinopia elements

**Comment by junghaelee** [comment]
Thank you!

**Comment by junghaelee** [comment]
I updated 'prop_set_rdai_p40k,xml.' Please let me know if you find any problems.

**Comment by briesenberg07** [comment]
Thanks @junghaelee ! I'll take a look at the new template and open some existing Item resources to test.

**Comment by briesenberg07** [comment]
Pulled updates to prop_set_rdai_P40k.xml, ran py/001_output_publish_load.py, received the following output + error message in terminal:

```
====================
GENERATING RDF/XML RESOURCE TEMPLATES
====================
====================
POST-PROCESSING RDF/XML TEMPLATES:
COMMENTING OUT REPEATING PROPERTY IRIS AND LABELS IN RESOURCE TEMPLATES
FILTERING AGENT PROPERTY TEMPLATES
SORTING RDF/XML DROP-DOWN PROPERTY TEMPLATES
====================
Traceback (most recent call last):
  File "C:\Users\ries07\od\gitrepos\sinopia_maps\py\001_output_publish_load.py", line 264, in <module>
    sort_alphabetical(f'{RT}')
  File "C:\Users\ries07\od\gitrepos\sinopia_maps\py\sort_multi_alphabet.py", line 5, in sort_alphabetical
    tree = ET.parse(file, parser)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3541, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1879, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1905, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1808, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1180, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 655, in lxml.etree._raiseParseError
OSError: Error reading file 'UWSINOPIA_WAU_rdaWork_collection_CAMS.rdf': failed to load external entity "UWSINOPIA_WAU_rdaWork_collection_CAMS.rdf"
```
Error message has **OSError: Error reading file 'UWSINOPIA_WAU_rdaWork_collection_CAMS.rdf': failed to load external entity "UWSINOPIA_WAU_rdaWork_collection_CAMS.rdf"**  

...I pulled changes to sinopia_maps before running 001, I have `UWSINOPIA_WAU_rdaWork_collection_CAMS.rdf` in my sinopia_maps repo where I'd expect it to be. So I'm unsure how to proceed.

@cspayne , would it be possible for you to take a look at this during your work time this week? (I'm not committing or pushing anything to sinopia_maps at this time; no updated templates have been loaded to stage. )

**Comment by cspayne** [comment]
@briesenberg07 
> Pulled updates to prop_set_rdai_P40k.xml, ran py/001_output_publish_load.py, received the following output + error message in terminal:

Did you make any changes before running the script that you haven't pushed? I didn't receive an error on my end. You may also try running it again and see if the problem repeats.

**Comment by briesenberg07** [comment]
Ha! I must've had some missing data in my local copy of the repo(s) when I first ran the script!? Worked just fine now. Sorry for the false alarm--thank you for taking a look @cspayne !

**Comment by cspayne** [comment]
Yay!!
________________________________

**Comment by briesenberg07** [comment]
More testing: Try 'Load RDF' using Item template JSON-LD --

![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/f100ab46-4a85-436c-93bc-7460eb99bc5b)

So, there must be an implementation set which has no property IRI and label??

**Comment by cspayne** [comment]
@briesenberg07 @junghaelee 

It looks like we lost some props in the rdai prop set file, where instead of the sinopia element getting deleted, the entire prop was deleted. 
I ran update_prop_sets.py to add those back in (and updated to v5.0.17) and ran 001_output_publish_load.py again and it seems to have solved the issue.

**Comment by briesenberg07** [comment]
A ha! I had ***not*** looked for missing `<prop>` elements, I was only looking in implementation_sets! Thank you @cspayne . Please push changes to map_storage if you haven't already.

This is a good note for @junghaelee and anyone editing prop_sets to be cautious not to delete prop elements! 

And, I'm not quite sure how this led to the errors we saw...

**Comment by junghaelee** [comment]
Thanks all! I’ll be more cautions next time!

Junghae

**Comment by cspayne** [comment]
@briesenberg07 
> And, I'm not quite sure how this led to the errors we saw...

I think the error was [here](https://github.com/uwlib-cams/map_storage/commit/34d7da4383e2ca5a58698fad47524642d29ca3fa#diff-d70aceaf800d5962ef1f819b7e4c15fc8693f3a695ca44b2c0aafd87e18921cbR963)! At some point, this label was changed, which resulted in a mismatched iri and label that Sinopia was unhappy with. Updating the prop_sets corrected this error.
