### ISSUE TITLE
NEED programmatic fix to avoid duplicate prop IRIs in one template

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#47]
Experiencing errors when the same property IRI is used more than once in the same template (except as in error message below).

![image](https://user-images.githubusercontent.com/27664966/178168178-e95bafe9-4530-40b2-ac09-b6dc0b86cc6e.png)

UWSINOPIA PTs can be set to include all subprops of a given prop as options for use in a property template. This is creating conflicts where `prop_set` > `prop` **A** is output to a PT in RT 001, and the same property IRI is output to a separate PT in RT 001 (`prop` **B**) as an option for use because it is a subprop of `prop` **B**. 

**For example:**

- `prop_set` > **creator agent of work** is output to RT 001 as a PT, set up to include all subprops as options for use in the PT
   - One of these subprops is **author agent**
- `prop_set` > **author agent** is also set up for output to RT 001 as a PT in order to provide subprops (such as **screenwriter agent**) for use in RT 001
- Thus, the IRI for **author agent** appears twice in RT 001, raising an error

~~It seems that it might be good to process RTs to~~ Let's modify the 001_* stylesheets (this would most likely be [001_05_multiple_properties.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/main/xsl/001_05_multiple_properties.xsl)) to avoid this, rather than having to manually identify conflicts and manually delete prop IRIs, etc..

Based on the example above, seems that the best way to process would be:

- When retrieving all subprops of a given prop for output to the PT (prop A PT) as options for use
- Identify whether or not each subprop is *also* output from a prop_set as it's own PT
- If yes, do *not* output this subprop IRI to the prop A PT

CC @mcm104 ; we discussed this on [2022-07-08](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/[2022_meetings.docx](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2022_meetings.docx?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=fxqNNS)?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=fxqNNS)

**Comment by briesenberg07** [comment]
**Failed attempt number one:**
```
[...]
               <xsl:for-each select="
                       document($rda_set_source)/rdf:RDF/rdf:Description
                       [rdfs:subPropertyOf/@rdf:resource = $prop/uwmaps:prop_iri/@iri]
                       [not(reg:status[@rdf:resource = 'http://metadataregistry.org/uri/RegStatus/1008'])]">
                   <xsl:choose>
                       <xsl:when test="
                               $sorted_properties[uwmaps:prop_iri/@iri = @rdf:about]/
                               uwmaps:sinopia/uwsinopia:implementation_set
                               [uwsinopia:institution = $institution]
                               [uwsinopia:resource = $resource]
                               [uwsinopia:format = $format]
                               [uwsinopia:user = $user]/node()">
                           <xsl:comment>
                               <xsl:text>USE PT FOR </xsl:text>
                               <xsl:value-of select="
                                       $sorted_properties[uwmaps:prop_iri/@iri = @rdf:about]
                                       /uwmaps:prop_label[@xml:lang = 'en']"/>
                           </xsl:comment>
                       </xsl:when>
                       <xsl:otherwise>
                           <sinopia:hasPropertyUri rdf:resource="{@rdf:about}"/>
                       </xsl:otherwise>
                   </xsl:choose>
               </xsl:for-each>
[...]
```

*Attempted this after passing the [sorted_properties](https://github.com/uwlib-cams/sinopia_maps/blob/228f7617ce5770d256a3f278e3523e80fb235b58/xsl/001_01_storage_to_rdfxml.xsl#L32-L50) node set created in 001_01 through to the 001_05_multiple_properties stylesheet > [multiple_property_iris template](https://github.com/uwlib-cams/sinopia_maps/blob/228f7617ce5770d256a3f278e3523e80fb235b58/xsl/001_05_multiple_properties.xsl#L17-L83).)*

**Comment by briesenberg07** [comment]
Note that this fix should also prevent the output of multiple rdfs:label triples for the given IRI. (I don't think that this prevents RT use, but is unnecessary.)

**Comment by briesenberg07** [comment]
Second failed attempt, as before, after passing `$sorted_properties` through to the `multiple_property_iris` template:
```
[...]
              <xsl:for-each select="
                      document($rda_set_source)/rdf:RDF/rdf:Description
                      [rdfs:subPropertyOf/@rdf:resource = $prop/uwmaps:prop_iri/@iri]
                      [not(reg:status[@rdf:resource = 'http://metadataregistry.org/uri/RegStatus/1008'])]">
                  <xsl:variable name="iri" select="@rdf:about"/>
                  <xsl:choose>
                      <xsl:when test="
                              $sorted_properties/uwmaps:prop[uwmaps:prop_iri/@iri = $iri]
                              /uwmaps:sinopia/uwsinopia:implementation_set
                              [uwsinopia:institution = $institution]
                              [uwsinopia:resource = $resource]
                              [uwsinopia:format = $format]
                              [uwsinopia:user = $user]">
                          <xsl:comment>
                              <xsl:text>USE PT FOR </xsl:text>
                              <xsl:value-of select="
                                      $sorted_properties/uwmaps:prop[uwmaps:prop_iri/@iri = $iri]
                                      /uwmaps:prop_label[@xml:lang = 'en']"/>
                          </xsl:comment>
                      </xsl:when>
                      <xsl:otherwise>
                          <sinopia:hasPropertyUri rdf:resource="{@rdf:about}"/>
                      </xsl:otherwise>
                  </xsl:choose>
              </xsl:for-each>
[...]
```

**Comment by briesenberg07** [comment]
Updating issue: This is now a "messy issue" because two (2) things need to be accomplished:

- Fix [001_05 stylesheet](https://github.com/uwlib-cams/sinopia_maps/blob/main/xsl/001_05_multiple_properties.xsl) so that multiple property IRIs are once again output
- And add the fix requested above

@mcm104 is working in branch [output_multiple_props](https://github.com/uwlib-cams/sinopia_maps/tree/output_multiple_props)

**Comment by mcm104** [comment]
So good news and... neutral news?

Good news: I have something that works some of the time ([link to code](https://github.com/uwlib-cams/sinopia_maps/blob/fa5ca4ce335700609fa3d78b459136faef0355e1/xsl/001_05_multiple_properties.xsl#L71)).

For whatever reason, I just couldn't get the $sorted_properties to work, so I just wrote the info we needed from the variable out in full in the test. (I think in the end, it's pretty much the same as your attempts, I just gave up on the $sorted_properties.)

[You can see some examples of it successfully generating comments here](https://github.com/uwlib-cams/sinopia_maps/blob/fa5ca4ce335700609fa3d78b459136faef0355e1/UWSINOPIA_WAU_rdaWork_monograph_CAMS.rdf#L193).

So I thought it was fine, and did a batch load into Sinopia Stage, but when I tried to open the work RT, I got this:

"A property template may not use the same property URI as another property template (http://rdaregistry.info/Elements/w/P10483, http://rdaregistry.info/Elements/w/P10495, http://rdaregistry.info/Elements/w/P10498, http://rdaregistry.info/Elements/w/P10451, http://rdaregistry.info/Elements/w/P10436, http://rdaregistry.info/Elements/w/P10448, http://rdaregistry.info/Elements/w/P10416, http://rdaregistry.info/Elements/w/P10463) unless both property templates are of type nested resource and the nested resources are of different classes."

(the neutral news)

I went and checked out rdaw:P10483 (has author collective agent), and saw that it [hadn't been written out as its own PT](https://github.com/uwlib-cams/map_storage/blob/96247f32d179af6400f934b8b38cbc5f5b643c05/prop_set_rdaw_p10k.xml#L255), but the actual issue was that it was listed a subproperty of two different properties ([has creator collective agent of work](https://github.com/uwlib-cams/sinopia_maps/blob/fa5ca4ce335700609fa3d78b459136faef0355e1/UWSINOPIA_WAU_rdaWork_monograph_CAMS.rdf#L559) and [has author agent](https://github.com/uwlib-cams/sinopia_maps/blob/fa5ca4ce335700609fa3d78b459136faef0355e1/UWSINOPIA_WAU_rdaWork_monograph_CAMS.rdf#L1120)).

I don't think it happens TOO often where an RDA property has multiple parent properties, but still, it obviously is enough to be a problem, so I'll start working on addressing that as well.

@briesenberg07

**Comment by briesenberg07** [comment]
@mcm104 thank you for surfacing this additional wrinkle, in which a given prop can be a subproperty of multiple properties, and therefore can appear in multiple Sinopia RT PTs, even if it is not the "main" property of any of these PTs. 

I don't have an answer yet to your question yet...

>  if a property can only be a subproperty in one PT, which PT do we choose...? e.g. in the above example, do we keep it under "has creator collective agent of work" or "has author agent"? How do we code it to make that decision...?

...but I wonder if we will need to add a processing step for the RDF/XML templates prior to loading to Sinopia (as opposed to a processing step when we output RDF/XML templates from prop_sets).

**Comment by mcm104** [comment]
[Just pushed my first attempt to the separate branch.](https://github.com/uwlib-cams/sinopia_maps/blob/output_multiple_props/xsl/004_remove_repeated_prop_URIs.xsl)

It's not working, but I'm not sure why...

```
                        <xsl:choose>
                            <xsl:when test="rdf:type/@rdf:resource='http://sinopia.io/vocabulary/PropertyTemplate'">
                                <xsl:variable name="node_id" select="@rdf:nodeID"/>
                                <rdf:Description rdf:nodeID="{$node_id}">
                                    <xsl:copy-of select="rdf:type"/>
                                    <xsl:copy-of select="rdfs:label"/>
                                    <xsl:for-each select="sinopia:hasPropertyUri">
                                        <xsl:variable name="prop_uri" select="@rdf:resource"/>
                                        <xsl:choose>
                                            <xsl:when test="/rdf:RDF/rdf:Description[not(@rdf:nodeID=$node_id)]/sinopia:hasPropertyUri/@rdf:resource=$prop_uri">
                                                <xsl:variable name="node_id_list" as="node()*">
                                                    <xsl:for-each select="/rdf:RDF/rdf:Description[sinopia:hasPropertyUri/@rdf:resource=$prop_uri]">
                                                        <xsl:copy-of select="@rdf:nodeID"/>
                                                    </xsl:for-each>
                                                </xsl:variable>
                                                <xsl:choose>
                                                    <xsl:when test="$node_id = $node_id_list[1]">
                                                        <xsl:copy-of select="."/>
                                                    </xsl:when>
                                                    <xsl:otherwise>
                                                        <xsl:comment> <xsl:copy-of select="."/> </xsl:comment>
                                                    </xsl:otherwise>
                                                </xsl:choose>
                                            </xsl:when>
                                            <xsl:otherwise>
                                                <xsl:copy-of select="."/>
                                            </xsl:otherwise>
                                        </xsl:choose>
                                    </xsl:for-each>
...
                                </rdf:Description>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:copy-of select="."/>
                            </xsl:otherwise>
                        </xsl:choose>
```

So what I'm trying to do here:
- For every property template...
- Copy all elements, minus sinopia:hasPropertyUri
- For each sinopia:hasPropertyUri...
- If there is a property template that is *not* the current PT that has this same property URI...
- Create variable list of node IDs for PTs that contain that property URI
- If current node ID is equal to the first node ID in variable...
- Copy current node (which should be sinopia:hasPropertyUri)
- If current node ID is NOT the first...
- Copy current node inside a comment

But when you look at the output ([example](https://github.com/uwlib-cams/sinopia_maps/blob/output_multiple_props/UWSINOPIA_WAU_rdaWork_monograph_CAMS_test.rdf)), the comments are empty, which tells me that it's not selecting anything, which is problematic because I use the same "<xsl:copy-of select="."/>" in other places... will investigate tomorrow

**Comment by mcm104** [comment]
Update: After some poking around, it seems like it's just that the xsl:copy-of doesn't work inside an xsl:comment; updated [here](https://github.com/uwlib-cams/sinopia_maps/blob/cd83010c78c0c1301494a1bc52cf0cdafb9b44e4/xsl/004_remove_repeated_prop_URIs.xsl#L49)

So it is working! Tried uploading to Sinopia Stage and was able to open the Work RT successfully!

To do now:
- Clean up the code
- Generate better comments
- See if I can maintain the comments generated in 001_05_multiple_properties.xsl
- Figure out best workflow -- right now, Oxygen is making me save the new output as separate files, because I can't read and overwrite a file in the same script in XSLT...

**Comment by mcm104** [comment]
Having more thoughts about workflow, could use some input @briesenberg07 ...

SO the issue inherent in XSLT that's bugging me is that you can't read and overwrite a file in the same transformation. This means that at present, the workflow would be...

- Run 001 stylesheets (propsets --> RTs)
- Run 004 stylesheet (comment out properties that are subprops of multiple props)
- (Optional) Manually delete old RTs with multiple conflicting properties (or else we have twice the number of RTs sitting in the repo; may also need to modify naming conventions so we have pre-transformation RTs and post-transformation RTs...) (could also write a Python script to do deleting/renaming, but this would still be another processing step)
- Upload the correct RTs to Sinopia

I had the thought of rewriting the new XSLT in Python instead, which allows you to read and overwrite a file in the same step. I would need to do some investigating on how to preserve comments, which shouldn't be too hard, and would give us this workflow:

- Run 001 stylesheets (propsets --> RTs)
- Run new Python script (comment out properties that are subprops of multiple props)
- Upload RTs to Sinopia

BUT then I also had the thought -- it feels kind of weird to be doing two steps of the same process --  commenting out repeating properties -- in two different scripts in two different coding languages (in 001_05 in XSLT for properties that are subproperties AND have their own PT filled out, and a new Python script for properties that are subproperties in multiple PTs). This makes me want to write a Python script that combines these steps into one. This feels neater in my head and doesn't change the workflow from option 2, but involves a little more coding work on my part (which I'm willing to do).

I'm curious what your thoughts on this are! Do we...

1. Keep it in XSLT because it's already done (minus maybe a Python script to do some simple organizing of files), even if it's a little messy,
2. Rewrite one part in Python for better workflow, or
3. Rewrite both parts in Python for better workflow AND (what I think is) more logical scripting?

Let me know if anything I wrote doesn't make sense to you!

**Comment by briesenberg07** [comment]
Hello @mcm104 and thank you for your comments here! 

Right, I experienced the error message below [1], and [we have it on the authority of Michael Kay that this is in fact a rule per the spec](https://stackoverflow.com/questions/56472663/overwrite-files-with-xslt) (I also experienced, as he mentions, my input file being wiped after the failed transformation).

# You say:

> Do we...
> 1. Keep it in XSLT because it's already done (minus maybe a Python script to do some simple organizing of files), even if it's a little messy,
> 2. Rewrite one part in Python for better workflow, or
> 3. Rewrite both parts in Python for better workflow AND (what I think is) more logical scripting?

## **I vote for \#3** if you are willing to write that code, but I'd like to confirm that I understand what this means:
- You've [added some processing steps to 001_05](https://github.com/uwlib-cams/sinopia_maps/blob/7c941a91d4837934aeb4625c0d3ea2a87c7ac382/xsl/001_05_multiple_properties.xsl#L70-L90) in your branch `output_multiple_props`. These steps take care of **CASE ONE**, where a subprop of a given prop_set > prop is also being output to the same RT as a PT. Your additions to the stylesheet prevent any such subprops from being output to the current PT, adding instead a comment. 
   - ***Would this stay or go?***
- You'll write some Python code. This will take care of:
   - ***[In the event that we don't keep your stylesheet additions above, **CASE ONE**]***
   - **CASE TWO**, which is when a given property is not output from any prop_set > prop to the RT, but because it is a subclass of more than one prop which is output to the RT, appears 2x or more in the RT and results in an error
   - NOTE that this code would take the place of your 004 stylesheet
   - NOTE that this Python code would allow us to overwrite the RDF/XML templates we process, allowing us to avoid outputting very similar duplicates, deleting older versions, taking care to load only the correct versions, etc., etc.

Am I caught up?

>>>

[1] - the error message I got trying a slightly modified testing version of [your 004 stylesheet](https://github.com/uwlib-cams/sinopia_maps/blob/7c941a91d4837934aeb4625c0d3ea2a87c7ac382/xsl/004_remove_repeated_prop_URIs.xsl)
>> System ID: C:\Users\Benjamin\OneDrive - UW\Desktop\004_test\004_bmr.xsl
Scenario: xslt_self_is_source_+_show_in_editor
XSL file: C:\Users\Benjamin\OneDrive - UW\Desktop\004_test\004_bmr.xsl
XML file: C:\Users\Benjamin\OneDrive - UW\Desktop\004_test\004_bmr.xsl
Engine name: Saxon-PE 10.6
Severity: fatal
Problem ID: XTRE1500
Description: Cannot read a document that was written during the same transformation: file:/C:/Users/Benjamin/OneDrive%20-%20UW/Desktop/004_test/TEST_UWSINOPIA_WAU_rdaAgent_na_CAMS.rdf
Start location: 23:59
Length: 1
URL: http://www.w3.org/TR/xslt20/#err-XTRE1500

**Comment by briesenberg07** [comment]
☝🏻 RELATED
If keeping branch `output_multiple_props` > [004 stylesheet](https://github.com/uwlib-cams/sinopia_maps/blob/7c941a91d4837934aeb4625c0d3ea2a87c7ac382/xsl/004_remove_repeated_prop_URIs.xsl), need to be sure and also copy over URI PT attributes and literal PT attributes (at present, looks like [only resource PT attributes and lookup PT attributes are copied over](https://github.com/uwlib-cams/sinopia_maps/blob/7c941a91d4837934aeb4625c0d3ea2a87c7ac382/xsl/004_remove_repeated_prop_URIs.xsl#L71-L75)).

**Comment by mcm104** [comment]
Yes -- if we're using your above definitions of case one and case two:

- Code to handle case one has already been written in XSLT and seems to be working just fine in the ouput_multiple_props branch, no issues
- Code to handle case two has been written in XSLT and it works BUT because of how XSLT works, it leads to a bad workflow

Of the three options I listed above:
- Option 2 means rewriting the code for case two in a new Python script, and leaving the code for case one alone.
- Option 3 means rewriting the code for cases one _and_ two in the same, new Python script.

So I'll start working on option 3! (And as you note, this would take place of the 004 script, and also the additions I previously made to the 001_05 script.)

**Comment by mcm104** [comment]
Option 3 looks like it's done! <https://github.com/uwlib-cams/sinopia_maps/blob/output_multiple_props/py/004_fix_multi_props.py>

At this point I think this only applies to the Work RT, which looks correct to me as far as comments go!
